In [1]:
import tensorflow as tf
import numpy as np

### Understanding Tensors

In [3]:
scalar=tf.constant(10)
print(scalar)

tf.Tensor(10, shape=(), dtype=int32)


In [4]:
vector=tf.constant([1,2,3])
print(vector)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.int16)
print("\nMatrix:", matrix)


Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)


In [7]:
zeros_tensor=tf.zeros(shape=(2,3))
zeros_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [8]:
ones_tensor=tf.ones(shape=(3,4))
ones_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
fill_tensor=tf.fill(dims=(2,3),value=99)
fill_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[99, 99, 99],
       [99, 99, 99]], dtype=int32)>

In [12]:
random_normal=tf.random.normal(shape=(2,3),stddev=1,mean=0)
random_normal

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.5126642 ,  0.17924388,  0.71957093],
       [-0.5274363 ,  1.9944761 , -0.7537368 ]], dtype=float32)>

In [14]:
numpy_array = np.array([[1.0, 2.0], [3.0, 4.0]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [15]:
numpy_from_tensor=tensor_from_numpy.numpy()
numpy_from_tensor

array([[1., 2.],
       [3., 4.]])

In [16]:
rank_2_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [17]:
rank_2_tensor[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [31]:
rank_2_tensor[0:1,:]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [38]:
rank_2_tensor[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [39]:
rank_2_tensor[0:1,1:3]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]], dtype=int32)>

### Tensor Operations

In [40]:
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
b = tf.constant([[5.0, 6.0], [7.0, 8.0]])
c = tf.constant(2.0)

# Addition
print("Addition (a + b):\n", a + b)
# Alternative using TensorFlow function
print("Addition (tf.add(a, b)):\n", tf.add(a, b))

# Subtraction
print("Subtraction (b - a):\n", b - a)
print("Subtraction (tf.subtract(b, a)):\n", tf.subtract(b, a))

# Element-wise Multiplication
print("Element-wise Multiplication (a * b):\n", a * b)
print("Element-wise Multiplication (tf.multiply(a, b)):\n", tf.multiply(a, b))

# Element-wise Division
print("Element-wise Division (b / a):\n", b / a)
print("Element-wise Division (tf.divide(b, a)):\n", tf.divide(b, a))

# Operations with scalars
print("Scalar Multiplication (a * c):\n", a * c)
print("Scalar Addition (a + c):\n", a + c)

Addition (a + b):
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Addition (tf.add(a, b)):
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Subtraction (b - a):
 tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
Subtraction (tf.subtract(b, a)):
 tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
Element-wise Multiplication (a * b):
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Element-wise Multiplication (tf.multiply(a, b)):
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Element-wise Division (b / a):
 tf.Tensor(
[[5.        3.       ]
 [2.3333333 2.       ]], shape=(2, 2), dtype=float32)
Element-wise Division (tf.divide(b, a)):
 tf.Tensor(
[[5.        3.       ]
 [2.3333333 2.       ]], shape=(2, 2), dtype=float32)
Scalar Multiplication (a * c):
 tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
Scalar Addition (a + c):
 tf.Tensor(
[[3. 4.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [41]:
# Example 1: Adding a scalar (shape ()) to a matrix (shape (2, 2))
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])
scalar = tf.constant(10.0)
result = matrix + scalar # Scalar is broadcast to [[10.0, 10.0], [10.0, 10.0]]
print("Matrix + Scalar:\n", result)

# Example 2: Adding a vector (shape (3,)) to a matrix (shape (2, 3))
matrix = tf.constant([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
vector = tf.constant([10, 20, 30])          # Shape (3,)
result = matrix + vector # Vector is broadcast across rows
# vector becomes [[10, 20, 30], [10, 20, 30]]
print("Matrix + Vector:\n", result)

# Example 3: Adding a column vector (shape (2, 1)) to a matrix (shape (2, 3))
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])       # Shape (2, 3)
col_vector = tf.constant([[10], [20]])             # Shape (2, 1)
result = matrix + col_vector # Column vector is broadcast across columns
# col_vector becomes [[10, 10, 10], [20, 20, 20]]
print("Matrix + Column Vector:\n", result)

# Example 4: Incompatible shapes (error)
matrix = tf.constant([[1, 2], [3, 4]]) # Shape (2, 2)
vector = tf.constant([10, 20, 30])      # Shape (3,)
try:
    result = matrix + vector
except tf.errors.InvalidArgumentError as e:
    print("\nError (Incompatible shapes):\n", e)

Matrix + Scalar:
 tf.Tensor(
[[11. 12.]
 [13. 14.]], shape=(2, 2), dtype=float32)
Matrix + Vector:
 tf.Tensor(
[[11 22 33]
 [14 25 36]], shape=(2, 3), dtype=int32)
Matrix + Column Vector:
 tf.Tensor(
[[11 12 13]
 [24 25 26]], shape=(2, 3), dtype=int32)

Error (Incompatible shapes):
 {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [2,2] vs. [3] [Op:AddV2] name: 


In [ ]:
a = tf.constant([[1, 2], 
                 [3, 4]])   # Shape (2, 2)
b = tf.constant([[5, 6], 
                 [7, 8]])   # Shape (2, 2)
c = tf.constant([[1, 2, 3], 
                 [4, 5, 6]]) # Shape (2, 3)

# Matrix multiplication using tf.matmul
matmul_ab = tf.matmul(a, b)
print("Matrix Multiplication (tf.matmul(a, b)):\n", matmul_ab)

# Matrix multiplication using @ operator
matmul_ab_operator = a @ b
print("Matrix Multiplication (a @ b):\n", matmul_ab_operator)

# Matrix multiplication with different compatible shapes
matmul_ac = tf.matmul(a, c) # (2, 2) @ (2, 3) -> (2, 3)
print("Matrix Multiplication (a @ c):\n", matmul_ac)

# Attempting incompatible shapes will raise an error
# try:
#    tf.matmul(c, a) # (2, 3) @ (2, 2) - Incompatible
# except tf.errors.InvalidArgumentError as e:
#    print("\nError (Incompatible shapes for matmul):\n", e)

# Contrast with element-wise multiplication
elementwise_ab = a * b
print("\nElement-wise Multiplication (a * b):\n", elementwise_ab)

Matrix Multiplication (tf.matmul(a, b)):
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Matrix Multiplication (a @ b):
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Matrix Multiplication (a @ c):
 tf.Tensor(
[[ 9 12 15]
 [19 26 33]], shape=(2, 3), dtype=int32)

Element-wise Multiplication (a * b):
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


### Variables in TensorFlow (mutable tensor)

In [43]:
scalar_var = tf.Variable(5.0, dtype=tf.float32)
print(f"Scalar Variable: {scalar_var}")

# Create a vector Variable from a list
vector_var = tf.Variable([1.0, 2.0, 3.0], name="my_vector") # Optional name
print(f"Vector Variable: {vector_var}")

# Create a matrix Variable from a NumPy array
matrix_var = tf.Variable(np.array([[1, 2], [3, 4]], dtype=np.int32))
print(f"Matrix Variable:\n{matrix_var}")

# Create a Variable from another Tensor
initial_tensor = tf.zeros((2, 2))
tensor_var = tf.Variable(initial_tensor)
print(f"Variable from Tensor:\n{tensor_var}")

Scalar Variable: <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>
Vector Variable: <tf.Variable 'my_vector:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>
Matrix Variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
Variable from Tensor:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>


In [44]:
# Using Variables in operations
result_tensor = scalar_var * 2.0 + vector_var[0]
print(f"\nOperation result (Tensor): {result_tensor}")

# Variables can be reshaped (creates a new Tensor)
reshaped_tensor = tf.reshape(matrix_var, (4,))
print(f"Reshaped Variable (Tensor): {reshaped_tensor}")

# Accessing the underlying Tensor value
print(f"\nVariable value as NumPy: {vector_var.numpy()}")



Operation result (Tensor): 11.0
Reshaped Variable (Tensor): [1 2 3 4]

Variable value as NumPy: [1. 2. 3.]


In [45]:
print(f"Original scalar_var: {scalar_var.numpy()}")

# Assign a new value
scalar_var.assign(10.0)
print(f"After assign(10.0): {scalar_var.numpy()}")

# Increment the value
scalar_var.assign_add(2.5)
print(f"After assign_add(2.5): {scalar_var.numpy()}")

# Decrement the value
scalar_var.assign_sub(1.0)
print(f"After assign_sub(1.0): {scalar_var.numpy()}")

# Assign can work with Tensors of compatible shape
new_vector_val = tf.constant([4.0, 5.0, 6.0])
vector_var.assign(new_vector_val)
print(f"\nVector variable after assign: {vector_var.numpy()}")


Original scalar_var: 5.0
After assign(10.0): 10.0
After assign_add(2.5): 12.5
After assign_sub(1.0): 11.5

Vector variable after assign: [4. 5. 6.]


In [46]:
# Example demonstrating gradient tracking
var_a = tf.Variable(2.0)
var_b = tf.Variable(3.0)

with tf.GradientTape() as tape:
  # Operations involving Variables are tracked
  y = var_a * var_a * var_b # y = a^2 * b

# Calculate gradients of y with respect to var_a and var_b
# dy/da = 2*a*b = 2*2*3 = 12
# dy/db = a^2 = 2^2 = 4
gradients = tape.gradient(y, [var_a, var_b])

print(f"\ny = {y.numpy()}")
print(f"Gradient dy/da: {gradients[0].numpy()}")
print(f"Gradient dy/db: {gradients[1].numpy()}")

# If a Variable is marked non-trainable, gradients are not tracked
non_trainable_var = tf.Variable(5.0, trainable=False)
with tf.GradientTape() as tape:
    z = non_trainable_var * 2.0
gradients_z = tape.gradient(z, [non_trainable_var])
print(f"\nGradient for non-trainable variable: {gradients_z[0]}") # Output will be None



y = 12.0
Gradient dy/da: 12.0
Gradient dy/db: 4.0

Gradient for non-trainable variable: None
