In [1]:
import torch

Empty tensor

In [5]:
torch.empty(1)

tensor([2.3694e-38])

In [6]:
torch.empty(2,3)

tensor([[-5.4529e+08,  9.4027e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

random tensor

In [7]:
torch.rand(2,3)

tensor([[0.9694, 0.9575, 0.5711],
        [0.9238, 0.9459, 0.0035]])

zero and ones

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.ones(1,2,3,dtype=torch.int16)

tensor([[[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int16)

list to tensor

In [12]:
torch.tensor([[1,2,3],[1,2,3]])

tensor([[1, 2, 3],
        [1, 2, 3]])

operations

In [15]:
x=torch.rand(2,3)
y=torch.rand(2,3)

print("x -->",x,"\n\n","y -->",y,"\n\n","x+y -->",x+y,"\n\n")

x --> tensor([[0.0513, 0.6233, 0.3158],
        [0.4632, 0.0973, 0.0712]]) 

 y --> tensor([[0.5175, 0.0551, 0.7492],
        [0.2066, 0.3018, 0.2992]]) 

 x+y --> tensor([[0.5688, 0.6784, 1.0650],
        [0.6698, 0.3991, 0.3704]]) 




In [16]:
x=torch.rand(2,3)
y=torch.rand(2,3)

print("x -->",x,"\n\n","y -->",y,"\n\n","x-y -->",x-y,"\n\n")

x --> tensor([[0.5747, 0.8464, 0.8696],
        [0.0878, 0.4504, 0.4280]]) 

 y --> tensor([[0.5349, 0.7841, 0.7663],
        [0.4081, 0.7826, 0.1425]]) 

 x-y --> tensor([[ 0.0399,  0.0623,  0.1033],
        [-0.3203, -0.3322,  0.2855]]) 




access elements

In [17]:
torch.ones(5,5)[:3,:4]

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
torch.ones(5,5)[1,1].item()

1.0

reshape

In [ ]:
x=torch.rand(4,4)
print(x)
y=x.view(-1,8)#smart reshaping 
print(y.shape)

tensor([[0.7202, 0.8622, 0.0811, 0.7047],
        [0.1860, 0.3842, 0.8773, 0.9621],
        [0.2656, 0.7389, 0.0360, 0.9259],
        [0.1714, 0.9613, 0.4515, 0.7214]])
torch.Size([2, 8])
