In [1]:
import torch

In [2]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 2.9228, -0.5680,  1.0949], requires_grad=True)


forward propagation

In [3]:
y=x+2
print(y)

tensor([4.9228, 1.4320, 3.0949], grad_fn=<AddBackward0>)


compute loss 

In [4]:
z=y*y*2
z=z.mean()
print(z)

tensor(23.9090, grad_fn=<MeanBackward0>)


backward propagation

In [5]:
z.backward()#dz/dx
print(x.grad)

tensor([6.5638, 1.9093, 4.1266])


prevent gradient history

In [6]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.7732, -0.6794,  2.1804], requires_grad=True)


In [7]:
x.detach()

tensor([ 0.7732, -0.6794,  2.1804])

In [8]:
with torch.no_grad():
    y=x+2
    print(y)

tensor([2.7732, 1.3206, 4.1804])


Training example

In [11]:
weights=torch.ones(4,requires_grad=True)


for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
